---
version: "2.1"
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=10000
      - PGID=10000
      - TZ=Africa/Johannesburg
      - WEBUI_PORT=8080
    volumes:
      - "./config:/config"
      - "/mnt:/data"
    restart: unless-stopped
    network_mode: "container:gluetun"