---

version: "3"
services:

  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8000:8000 # Remote Control VPN
      - 9117:9117 # Jackett
      - 6881:6881 # qbittorrent tcp
      - 6881:6881/udp # qbittorrent udp
      - 8080:8080 # qbittorrent webui
    volumes:
      - "./config/gluetun:/gluetun"
    env_file:
      - ./.env
    restart: unless-stopped
    networks:
      reverse-proxy:
        aliases:
          - qluetun

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=10000
      - PGID=10000
      - TZ=Africa/Johannesburg
      - WEBUI_PORT=8080
    volumes:
      - "./config/qbittorrent:/config"
      - "/mnt:/data"
    restart: unless-stopped
    depends_on:
      - gluetun
    network_mode: "service:gluetun"

  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=10000
      - PGID=10000
      - TZ=Africa/Johannesburg
      - AUTO_UPDATE=true
    volumes:
      - "./config/jackett:/config"
      - "/mnt:/data"
    restart: unless-stopped
    depends_on:
      - gluetun
    network_mode: "service:gluetun"

networks:
  reverse-proxy:
    external:
      name: reverse-proxy