version: "3"
services:
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
#      - ./config/config.json:/config.json:ro
    command: --schedule="0 0 1 * * *" --rolling-restart=true --remove-volumes=true