version: "3"
services:
  db_recipes:
    restart: always
    image: postgres:11-alpine
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    env_file:
      - ./.env
    networks:
      - internal

  web_recipes:
    image: vabene1111/recipes
    restart: always
    env_file:
      - ./.env
    volumes:
      - staticfiles:/opt/recipes/staticfiles
      - ./mediafiles:/opt/recipes/mediafiles
    depends_on:
      - db_recipes
    networks:
      - internal

  nginx_recipes:
    image: nginxinc/nginx-unprivileged:mainline-alpine
    user: "1000"
    restart: always
    env_file:
      - ./.env
    depends_on:
      - web_recipes
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro
      - staticfiles:/static
      - ./mediafiles:/media
    networks:
      internal:
      reverse-proxy:
        aliases:
          - tandoor

volumes:
  staticfiles:

networks:
  internal:
  reverse-proxy:
    external:
      name: reverse-proxy